### ISSUE TITLE
为什么不能自动翻页呢

### ISSUE THREAD

**Issue by Amatuki** [wangshub/Douyin-Bot#20]
按教程说的做了，可是没什么反应

**Comment by JasonKhew96** [comment]
[Here](https://github.com/wangshub/Douyin-Bot#%E6%B3%A8%E6%84%8F)
- 目前暂时只适配了一加5(1920x1080 分辨率)，如果手机不是该分辨率，请修改 config/ 文件夹下面的配置文件；
- config.json配置文件参考：
  - center_point: 屏幕中心点(x, y)，区域范围 rx, ry
  - follow_bottom: 关注按钮位置(x, y)，区域范围 rx, ry
  - star_bottom: 点赞按钮位置(x, y)，区域范围 rx, ry
