### ISSUE TITLE
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

### ISSUE THREAD

**Issue by vatezj** [wangshub/Douyin-Bot#21]
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

**Comment by eanfs** [comment]
me too

**Comment by wangshub** [comment]
试一下在 Python 3.6 下面运行 @vatezj

**Comment by eanfs** [comment]
![image](https://user-images.githubusercontent.com/5432110/41197571-2992a2be-6c96-11e8-8ca7-ba434a4b5833.png)

**Comment by zhwx600** [comment]
我也是啊 ，怎么办呢？。。。

**Comment by lihuimintu** [comment]
目测是版本问题带来的，我是mac os ，最先之前是官网下载的安装包，3.6.1 然后报这个错，后端用brew 下载python3 给我下载是python3.7 还是不行，最后借助google用brew 下载了python3.6.5，运行就可以了

**Comment by Akiract** [comment]
我装了3.6.5怎么还是这个错误！！
