### ISSUE TITLE
这个是如何推算是美女的？

### ISSUE THREAD

**Issue by NathanDataPlayer** [wangshub/Douyin-Bot#22]
通过照片的像素切割后，然后跟自己设立的标准对比？？

**Comment by tuzimoe** [comment]
腾讯 AI 开放平台 人脸识别 API 会返回 响应参数
gender 性别 [0~100]（越接近0越倾向为女性，越接近100越倾向为男性）
在源码中设定了小于 50 判定为女性

**Comment by huanhuande** [comment]
是接入的第三方的AI平台吗？

**Comment by wangshub** [comment]
ai.qq.com @huanhuande

**Comment by huanhuande** [comment]
喔 我看到了
