### ISSUE TITLE
请问如何根据手机分辨率如何进行定位,希望能给个教程或者工具,谢谢

### ISSUE THREAD

**Issue by aoyoo111** [wangshub/Douyin-Bot#23]
请问如何根据手机分辨率如何进行定位,希望能给个教程或者工具,谢谢

**Comment by wangshub** [comment]
@aoyoo111 https://github.com/wangshub/Douyin-Bot#%E6%B3%A8%E6%84%8F

像素点位置，你可以用一些图片浏览器定位，鼠标放上去就能显示当前坐标，如

- GIMP
- https://yangcha.github.io/iview/iview.html

**Comment by wangshub** [comment]
@aoyoo111 如果打开配置文件失败，就回去找 default.json。  rx,ry 是区域单位，在这个范围内随机点击用的

**Comment by aoyoo111** [comment]
@wangshub 明白了,感谢感谢!
