### ISSUE TITLE
找了同一个人的两张照片试了一下人脸识别

### ISSUE THREAD

**Issue by BIGMONK** [wangshub/Douyin-Bot#24]
开美颜：年龄21，魅力值：76，表情：眉开眼笑；不开美颜显示年龄27，魅力值：100，表情：笑尽妖娆；人脸对比相似度94%；所以这个人脸接口找到的真的全是漂亮的吗

**Comment by wangshub** [comment]
仅供参考，不代表作者真实立场哈 @BIGMONK
