### ISSUE TITLE
调用腾讯api接口失败

### ISSUE THREAD

**Issue by hfstack** [wangshub/Douyin-Bot#41]
[JSON object must be str, not 'bytes'](https://stackoverflow.com/questions/35192694/json-object-must-be-str-not-bytes)
{“ret”: -1}

**Comment by hfstack** [comment]
修改common/apiutil.py 文件
 def invoke(self, params):
        self.url_data = urllib.parse.urlencode(params).encode("utf-8")
        req = urllib.request.Request(self.url, self.url_data)
        try:
            rsp = urllib.request.urlopen(req)
            str_rsp = rsp.read()
            dict_rsp = json.loads(**str_rsp.decode()**)
            print(dict_rsp)
            return dict_rsp
        except Exception as e:
            print(e)
            return {'ret': -1}

**Comment by dlmgis** [comment]
check_screenshot函数运行结果为不支持当前设备，什么机型可以截屏？我的手机可以运行跳一跳辅助为什么在这个项目这里出现截屏问题？vivo y55a的手机

**Comment by wangshub** [comment]
@hfstack 
- 请以 Markdown 格式书写 Issue comment
- 修改过后，问题是否解决？

**Comment by hfstack** [comment]
问题解决了
