### ISSUE TITLE
如何自动识别抖音视频？

### ISSUE THREAD

**Issue by hdxjl** [wangshub/Douyin-Bot#43]
我想对B站的抖音视频集合进行操作，像您一样检测小姐姐颜值再OCR抖音ID然后关注。请问要如何在正确的时间点截屏？因为有些小姐姐开始的时候是不露正脸的。因为有一些视频是从火山等平台扒的，如何检测右下角logo和id变化，要用什么库呢？万分感谢

**Comment by wangshub** [comment]
@hdxjl 
- 你这个是逻辑上的更改，基本不涉及别的库
- 可以 Fork 我的代码，按照你的想法改下主程序 `Douyin-bot.py`
