### ISSUE TITLE
我跑通了，为什么但是不会有截图呢？日志显示the JSON object must be str, not 'bytes'{'ret': -1}

### ISSUE THREAD

**Issue by zhongqian** [wangshub/Douyin-Bot#49]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
Device: gemini
Phone OS: 8.0.0
Host OS: win32
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
**********
shell screencap -p /sdcard/autojump.png
pull /sdcard/autojump.png .
shell input swipe 540 1265 540 965 200
shell screencap -p /sdcard/autojump.png
pull /sdcard/autojump.png .
the JSON object must be str, not 'bytes'
{'ret': -1}
shell input swipe 540 1265 540 965 200
shell screencap -p /sdcard/autojump.png
pull /sdcard/autojump.png .
the JSON object must be str, not 'bytes'
{'ret': -1}
shell input swipe 540 1265 540 965 200
shell screencap -p /sdcard/autojump.png

**Comment by privatez** [comment]
#30 看看这个issue

**Comment by zhongqian** [comment]
apituil.py 42行dict_rsp = json.loads(str_rsp.decode('utf-8'))
python3.5已解决
