### ISSUE TITLE
解释一下配置文件的信息吧，如何不同手机怎么配置

### ISSUE THREAD

**Issue by binyoucai** [wangshub/Douyin-Bot#5]
{

"center_point":{

"x": 540,

"y": 965,

"rx": 10,

"ry": 300

},

"follow_bottom":{

"x": 990,

"y": 950,

"rx": 10,

"ry": 10

},

"star_bottom":{

"x": 1000,

"y": 1083,

"rx": 10,

"ry": 10

}

 

}

**Comment by binyoucai** [comment]
有没有兴趣写个欢乐球球辅助，就是微信上面那个小游戏

**Comment by wangshub** [comment]
@binyoucai 已添加 https://github.com/wangshub/Douyin-Bot#%E6%B3%A8%E6%84%8F
