### ISSUE TITLE
大家都冷静一下，我找到一个lz的致命bug。

### ISSUE THREAD

**Issue by linkingli** [wangshub/Douyin-Bot#74]
如果妹子化妆或者使用美颜，那么获取的data是有很多的noise的，所以为了保证code不报bug,我建议8.27号为不化妆日。。=-=

**Comment by zgmd** [comment]
你这中英文切换自如啊，你就是抖音上的大神吧

**Comment by xvxieweilai** [comment]
> 如果妹子化妆或者使用美颜，那么获取的data是有很多的noise的，所以为了保证code不报bug,我建议8.27号为不化妆日。。=-=

在家都不会化妆、但是开相机必开美颜。治不了

**Comment by linkingli** [comment]
close
